# Generated by Django 5.0.1 on 2024-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Items', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
